print("hello folks")
a=int(input("enter first number   "))
b=int(input("enter second number   "))
print("the sum is", a+b)
print("the difference is", a-b)
print("the product is", a*b)
print("the division is", a/b)
print("the mod is", a%b)